# examples:
#   prd: 123.45.1.0/24
#     web: 0000 0001
#     app: 0001 0001
#     batch: 0010 0001
#   stg: 123.45.2.0/24
#   dev: 123.45.3.0/24

yml2conf:
  version: 1.0

configs:

  - { Host: web1,   HostName: 123.45.1.1, Port: 22, User: dev, IdentityFile: ~/.ssh/prd }
  - { Host: web2,   HostName: 123.45.1.2, Port: 22, User: dev, IdentityFile: ~/.ssh/prd }
  - { Host: web3,   HostName: 123.45.1.3, Port: 22, User: dev, IdentityFile: ~/.ssh/prd }
  - { Host: web4,   HostName: 123.45.1.4, Port: 22, User: dev, IdentityFile: ~/.ssh/prd }
  - { Host: app1,   HostName: 123.45.1.17, Port: 22, User: dev, IdentityFile: ~/.ssh/prd }
  - { Host: app2,   HostName: 123.45.1.18, Port: 22, User: dev, IdentityFile: ~/.ssh/prd }
  - { Host: batch1, HostName: 123.45.1.33, Port: 22, User: dev, IdentityFile: ~/.ssh/prd }
  - { Host: batch2, HostName: 123.45.1.34, Port: 22, User: dev, IdentityFile: ~/.ssh/prd }

  - { Host: stg-web1,   HostName: 123.45.2.1, Port: 22, User: dev, IdentityFile: ~/.ssh/stg }
  - { Host: stg-web2,   HostName: 123.45.2.2, Port: 22, User: dev, IdentityFile: ~/.ssh/stg }
  - { Host: stg-web3,   HostName: 123.45.2.3, Port: 22, User: dev, IdentityFile: ~/.ssh/stg }
  - { Host: stg-web4,   HostName: 123.45.2.4, Port: 22, User: dev, IdentityFile: ~/.ssh/stg }
  - { Host: stg-app1,   HostName: 123.45.2.17, Port: 22, User: dev, IdentityFile: ~/.ssh/stg }
  - { Host: stg-app2,   HostName: 123.45.2.18, Port: 22, User: dev, IdentityFile: ~/.ssh/stg }
  - { Host: stg-batch1, HostName: 123.45.2.33, Port: 22, User: dev, IdentityFile: ~/.ssh/stg }
  - { Host: stg-batch2, HostName: 123.45.2.34, Port: 22, User: dev, IdentityFile: ~/.ssh/stg }

  - { Host: dev-web1,   HostName: 123.45.3.1, Port: 22, User: dev, IdentityFile: ~/.ssh/dev }
  - { Host: dev-web2,   HostName: 123.45.3.2, Port: 22, User: dev, IdentityFile: ~/.ssh/dev }
  - { Host: dev-app1,   HostName: 123.45.3.17, Port: 22, User: dev, IdentityFile: ~/.ssh/dev }
  - { Host: dev-batch1, HostName: 123.45.3.33, Port: 22, User: dev, IdentityFile: ~/.ssh/dev }
